import { CharacterClassConfig, CharacterClassId, AvatarTier, RpgTitle, AvatarOption } from "./types";

export const CHARACTER_CLASSES: Record<CharacterClassId, CharacterClassConfig> = {
  clerc: {
    id: "clerc",
    name: "Clerc Auscultateur",
    subtitle: "Maître du Rythme & de l'Hémodynamique",
    role: "Médecine, Urgences & Cardiologie",
    lore: "Initié aux mystères acoustiques du cœur, il entend les murmures pathologiques et discerne chaque battement de la vie.",
    color: "#f43f5e",
    accentColor: "rose-500",
    bgGradient: "from-rose-500/20 via-rose-600/10 to-slate-900",
    badgeBg: "bg-rose-500/15 text-rose-300 border-rose-500/30",
    borderColor: "border-rose-500",
    passiveName: "Égide Clinique",
    passiveShort: "1ère erreur pardonnée",
    passiveDescription: "La première erreur commise dans un donjon n'inflige aucun dégât de PV.",
    classSpellId: "divine_diagnosis",
    classSpellName: "Diagnostic Divin",
    classSpellDescription: "Révèle et élimine instantanément une mauvaise option (cooldown 3 combats).",
    weaponSignature: "Stéthoscope de Lumière",
    iconName: "Stethoscope",
    stats: {
      auscultation: 95,
      biologie: 70,
      ecg: 80,
      palpation: 75,
    },
  },
  alchimiste: {
    id: "alchimiste",
    name: "Alchimiste Biochimiste",
    subtitle: "Sorcier des Biomarqueurs & Formules",
    role: "Pharmacie, Biologie & Toxicologie",
    lore: "Pourfendeur de l'invisible, il dose les enzymes cellulaires et transmute les bilans sanguins en diagnostics certains.",
    color: "#10b981",
    accentColor: "emerald-500",
    bgGradient: "from-emerald-500/20 via-teal-600/10 to-slate-900",
    badgeBg: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30",
    borderColor: "border-emerald-500",
    passiveName: "Transmutation d'XP",
    passiveShort: "+20% XP sur biomarqueurs",
    passiveDescription: "Chaque association correcte et diagnostic de biologie accorde +20% d'XP.",
    classSpellId: "spectral_analysis",
    classSpellName: "Analyse Spectrale",
    classSpellDescription: "Déclenche un 50/50 gratuit sans dépenser de mana (cooldown 2 combats).",
    weaponSignature: "Fiole de Troponine Pure",
    iconName: "FlaskConical",
    stats: {
      auscultation: 65,
      biologie: 98,
      ecg: 75,
      palpation: 60,
    },
  },
  mage_ecg: {
    id: "mage_ecg",
    name: "Mage Rythmologue",
    subtitle: "Archimage de l'Électrophysiologie",
    role: "Électrocardiographie & Rythmologie",
    lore: "Canalisateur des flux électriques myocardiques, il déchiffre les ondes P-Q-R-S-T et dompte les tempêtes rythmiques.",
    color: "#6366f1",
    accentColor: "indigo-500",
    bgGradient: "from-indigo-500/20 via-purple-600/10 to-slate-900",
    badgeBg: "bg-indigo-500/15 text-indigo-300 border-indigo-500/30",
    borderColor: "border-indigo-500",
    passiveName: "Vision Arcanique",
    passiveShort: "Loupe sur tracés ECG",
    passiveDescription: "Surligne automatiquement les anomalies morphologiques sur les tracés ECG.",
    classSpellId: "temporal_vision",
    classSpellName: "Vision Temporelle",
    classSpellDescription: "Ralentit le timer de 50% pour ce combat (cooldown 3 combats).",
    weaponSignature: "Sceptre Galvanométrique",
    iconName: "Zap",
    stats: {
      auscultation: 75,
      biologie: 75,
      ecg: 98,
      palpation: 65,
    },
  },
  moine: {
    id: "moine",
    name: "Moine Biomécanicien",
    subtitle: "Gardien du Toucher & des Pouls",
    role: "Kinésithérapie, Ostéopathie & Anatomie",
    lore: "Maître de l'examen physique méthodique, ses mains détectent le moindre frémissement vasculaire et les tensions tissulaires.",
    color: "#f59e0b",
    accentColor: "amber-500",
    bgGradient: "from-amber-500/20 via-orange-600/10 to-slate-900",
    badgeBg: "bg-amber-500/15 text-amber-300 border-amber-500/30",
    borderColor: "border-amber-500",
    passiveName: "Toucher Médical",
    passiveShort: "+1 Vie sur épreuves palpation",
    passiveDescription: "Bonus de PV et de précision dans les simulateurs de tension et pouls.",
    classSpellId: "iron_stance",
    classSpellName: "Posture de Fer",
    classSpellDescription: "Immunise contre les dégâts de la prochaine erreur (cooldown 2 combats).",
    weaponSignature: "Gantelet de Palpation",
    iconName: "Activity",
    stats: {
      auscultation: 80,
      biologie: 60,
      ecg: 70,
      palpation: 98,
    },
  },
  necromancien: {
    id: "necromancien",
    name: "Nécromancien Urgentiste",
    subtitle: "Sentinelle de la Réanimation",
    role: "Urgences, Réanimation & SAMU",
    lore: "Il arrache les âmes aux griffes du choc cardiogénique et des arrêts cardiorespiratoires.",
    color: "#8b5cf6",
    accentColor: "purple-500",
    bgGradient: "from-purple-500/20 via-slate-900 to-slate-950",
    badgeBg: "bg-purple-500/15 text-purple-300 border-purple-500/30",
    borderColor: "border-purple-500",
    passiveName: "Adrénaline Pure",
    passiveShort: "+10s sur timers d'urgence",
    passiveDescription: "Accorde 10 secondes supplémentaires sur toutes les questions d'urgence vitale.",
    classSpellId: "resurrection",
    classSpellName: "Défibrillation d'Âme",
    classSpellDescription: "Ressuscite le héros avec 25 PV en cas de défaite (1x/jour, cooldown 4 combats).",
    weaponSignature: "Pales de Défibrillateur Arcaniques",
    iconName: "ShieldAlert",
    stats: {
      auscultation: 85,
      biologie: 80,
      ecg: 90,
      palpation: 85,
    },
  },
  enchanteuse: {
    id: "enchanteuse",
    name: "Enchanteuse Neurologue",
    subtitle: "Tisseuse des Synapses & Réflexes",
    role: "Neurologie, Psychiatrie & Neurosciences",
    lore: "Elle lit dans les faisceaux pyramidaux et dénoue les syndromes méningés avec une précision chirurgicale.",
    color: "#ec4899",
    accentColor: "pink-500",
    bgGradient: "from-pink-500/20 via-slate-900 to-slate-950",
    badgeBg: "bg-pink-500/15 text-pink-300 border-pink-500/30",
    borderColor: "border-pink-500",
    passiveName: "Mnémosyne",
    passiveShort: "Marque les questions déjà vues",
    passiveDescription: "Affiche en surbrillance les questions déjà maîtrisées pour un rappel instantané.",
    classSpellId: "mental_clarity",
    classSpellName: "Clarté Mentale",
    classSpellDescription: "Restaure instantanément +30 PV (cooldown 3 combats).",
    weaponSignature: "Marteau Réflexe de Cristal",
    iconName: "Brain",
    stats: {
      auscultation: 70,
      biologie: 85,
      ecg: 75,
      palpation: 90,
    },
  },
  chasseur: {
    id: "chasseur",
    name: "Chasseur Pneumologue",
    subtitle: "Pisteur des Souffles & Râles",
    role: "Pneumologie & Physiologie Respiratoire",
    lore: "Il traque les râles crépitants et débusque les sibilants au plus profond de l'arbre bronchique.",
    color: "#06b6d4",
    accentColor: "cyan-500",
    bgGradient: "from-cyan-500/20 via-slate-900 to-slate-950",
    badgeBg: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30",
    borderColor: "border-cyan-500",
    passiveName: "Flair Clinique",
    passiveShort: "1 Indice gratuit par donjon",
    passiveDescription: "Débloque un indice mnémotechnique sans coût de mana par donjon exploré.",
    classSpellId: "truth_arrow",
    classSpellName: "Flèche de Vérité",
    classSpellDescription: "Confirme si une option Vrai/Faux est exacte avant validation (cooldown 2 combats).",
    weaponSignature: "Spiromètre d'Éther",
    iconName: "Wind",
    stats: {
      auscultation: 92,
      biologie: 75,
      ecg: 70,
      palpation: 85,
    },
  },
  gardien: {
    id: "gardien",
    name: "Gardien Pédiatre",
    subtitle: "Protecteur des Petits Héros",
    role: "Pédiatrie, Néonatologie & Développement",
    lore: "Bouclier bienveillant, il adapte chaque démarche sémiologique à la physiologie délicate de l'enfant.",
    color: "#14b8a6",
    accentColor: "teal-500",
    bgGradient: "from-teal-500/20 via-slate-900 to-slate-950",
    badgeBg: "bg-teal-500/15 text-teal-300 border-teal-500/30",
    borderColor: "border-teal-500",
    passiveName: "Aura Protectrice",
    passiveShort: "-20% dégâts sur erreurs pièges",
    passiveDescription: "Réduit de 20 % les points de vie perdus sur les questions pièges.",
    classSpellId: "wisdom_shield",
    classSpellName: "Bouclier de Sagesse",
    classSpellDescription: "Immunité totale aux dégâts pendant 20 secondes (cooldown 3 combats).",
    weaponSignature: "Toise Enchantée",
    iconName: "Shield",
    stats: {
      auscultation: 88,
      biologie: 80,
      ecg: 80,
      palpation: 90,
    },
  },
};

export const RPG_TITLES: RpgTitle[] = [
  { level: 1, title: "Initié Sémiologue", description: "Fait ses premiers pas dans l'art de l'interrogatoire clinique." },
  { level: 2, title: "Apprenti Auscultateur", description: "Distingue les bruits B1 et B2 au lit du patient." },
  { level: 3, title: "Pourfendeur de l'Angor", description: "Reconnaît immédiatement la douleur thoracique coronarienne." },
  { level: 4, title: "Gardien du Rythme Sinusal", description: "Dompte les tracés électriques et identifie les extrasystoles." },
  { level: 5, title: "Mage des Bruits & Souffles", description: "Déchiffre les irradiations et manœuvres dynamiques sans hésiter." },
  { level: 6, title: "Grand Alchimiste des Enzymes", description: "Interprète avec brio la cinétique des troponines et du BNP." },
  { level: 8, title: "Commandeur de l'Hémodynamique", description: "Maîtrise la pression artérielle et les signes d'insuffisance cardiaque." },
  { level: 10, title: "Archimage Sémiologue Suprême", description: "Incarnation vivante de la démarche clinique méthodique et infaillible." },
];

export const AVATAR_OPTIONS: AvatarOption[] = [
  { id: "clerc_1", classId: "clerc", name: "Valère l'Auscultateur", gender: "m", variant: 1, tier: "apprenti" },
  { id: "clerc_2", classId: "clerc", name: "Éléonore du Rythme", gender: "f", variant: 2, tier: "apprenti" },
  { id: "alchimiste_1", classId: "alchimiste", name: "Nicolas le Doseur", gender: "m", variant: 1, tier: "apprenti" },
  { id: "alchimiste_2", classId: "alchimiste", name: "Sybille des Flacons", gender: "f", variant: 2, tier: "apprenti" },
  { id: "mage_ecg_1", classId: "mage_ecg", name: "Éole des Tracés", gender: "m", variant: 1, tier: "apprenti" },
  { id: "mage_ecg_2", classId: "mage_ecg", name: "Astrid la Fulgurante", gender: "f", variant: 2, tier: "apprenti" },
  { id: "moine_1", classId: "moine", name: "Gaspard du Pouls", gender: "m", variant: 1, tier: "apprenti" },
  { id: "moine_2", classId: "moine", name: "Théa la Praticienne", gender: "f", variant: 2, tier: "apprenti" },
  { id: "necromancien_1", classId: "necromancien", name: "Lazare le Réanimateur", gender: "m", variant: 1, tier: "apprenti" },
  { id: "enchanteuse_1", classId: "enchanteuse", name: "Morgane des Synapses", gender: "f", variant: 1, tier: "apprenti" },
  { id: "chasseur_1", classId: "chasseur", name: "Robin des Bronches", gender: "m", variant: 1, tier: "apprenti" },
  { id: "gardien_1", classId: "gardien", name: "Galahad le Protecteur", gender: "m", variant: 1, tier: "apprenti" },
];

export function getClassConfig(classId?: string | null): CharacterClassConfig {
  if (classId && classId in CHARACTER_CLASSES) {
    return CHARACTER_CLASSES[classId as CharacterClassId];
  }
  return CHARACTER_CLASSES.clerc;
}

export function getTitleForLevel(level: number): string {
  const eligibleTitles = RPG_TITLES.filter((t) => t.level <= level);
  if (eligibleTitles.length === 0) return "Initié Sémiologue";
  return eligibleTitles[eligibleTitles.length - 1].title;
}

export function getAvatarTier(level: number): AvatarTier {
  if (level >= 10) return "archimage";
  if (level >= 5) return "initie";
  return "apprenti";
}
